### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by Crypto-Abysmol** [ersantiago/eth_brutdrv#1]
in VS:

Traceback (most recent call last):
  File "/home/Downloads/eth_brutdrv-main/brutdrv.py", line 3, in <module>
    from bip_utils import Bip32
ImportError: cannot import name 'Bip32' from 'bip_utils' (/.local/lib/python3.10/site-packages/bip_utils/__init__.py)

**Comment by ersantiago** [comment]
You'll need to install the required modules
